language: python
python: 3.5
sudo: false

branches:
    only:
        - master
        - /^\d\.\d+$/

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36

addons:
    apt:
        packages:
            - python-numpy
            - python-scipy
            - libatlas-base-dev
            - liblapack-dev
            - gfortran
            - cmake

install:
    - make get-deps
    - pip install -U pip tox codecov

script: tox

after_success:
    - python install_wapiti.py
    - cd Wapiti; make; make install; cd ..
    - codecov

cache:
    directories:
        - $HOME/.cache/pip
